# Generated by Django 3.2.7 on 2022-04-25 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_date', models.DateField()),
                ('total_corr', models.IntegerField(blank=True, null=True)),
                ('total_wrong', models.IntegerField(blank=True, null=True)),
                ('max_marks', models.IntegerField()),
                ('scored_marks', models.IntegerField(default=0)),
                ('percentage', models.FloatField()),
                ('quiz_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.quizname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuizDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.quizquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.quizoption')),
            ],
        ),
    ]
