# Generated by Django 3.2.7 on 2022-04-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_userquizdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuizDetail',
        ),
    ]
