# Generated by Django 3.2.7 on 2022-04-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_userquizdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuizDetail',
        ),
    ]
