# Generated by Django 3.2.7 on 2022-04-26 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
        ('student', '0006_delete_userquizdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.userquizsummary')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.quizoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.quizquestion')),
                ('quiz_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.quizname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
