# Generated by Django 3.2.7 on 2022-04-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProcess', '0002_auto_20220423_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='QuizName',
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
